# -*- coding: utf-8 -*-
"""calculate descriptive summary statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHDJ7C1O220w3eEKKOG78p-iaYlOjY4w

**Practical No. 1-B: Load a dataset, calculate descriptive summary statistics, create visualizations using different graphs, and identify potential features and target variables.**

---
"""

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/DataSet ML/train.csv")
print(df.head())

"""**Calculate Descriptive Summary Statics**"""

print(df.describe())

"""**Additional Summary Statictics**"""

print(df.describe(include='all'))

"""**Identify potential features and target variables**"""

x = df.drop('Survived', axis=1)
y = df['Survived']
# print(x.head())
# print(y.head())
print("Features :\n",x)
print("Target Variable :\n",y)

"""**Create visualizations using different graphs**
**Histogram**

"""

import matplotlib.pyplot as plt
df.hist(figsize=(10, 8)) # create hist for numeric data with adjusted figure size
plt.suptitle('descriptive summary statistics') # Add a title to the entire figure
plt.show() # show plt

"""**Column Chart**"""

import matplotlib.pyplot as plt
df.plot.bar()
plt.bar(df['Age'], df['Pclass'])
plt.xlabel('Age')
plt.ylabel('Pclass')
plt.xticks(df['Age'][::10])
plt.show()

plt.scatter(df['Pclass'],df['Age'])
plt.xlabel('Pclass')
plt.ylabel('Age')

plt.show()

import seaborn as sns
sns.boxplot(x='Pclass', y='Age', data=df)
plt.show()