# -*- coding: utf-8 -*-
"""Data Pre-processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1312XUqRovD-rqM-_feKOhUSJL5lHT1Zv

**Practical No. 1-A: Data Pre-processing and Exploration Load a CSV dataset. Handle missing values, inconsistent formatting, and
outliers**


---
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/DataSet ML/SampleData.csv')
print(df)

"""**Handling Missing values**"""

print(df.info())

"""**Displaying All Details of Name Column**




"""

print(df['Name'])

print(df.isnull())

"""**Replaing NaN Value with "null"**"""

df.fillna("NAME",inplace=True)
print(df.Name)

"""**Handling inconsistent formatting**

1. **Standardizing Text Data - a. Convert to Lowercase or Uppercase and vice versa**
"""

df.Name = df.Name.str.lower()
df.Name

df.Name = df.Name.str.upper()
df.Name

"""**b. Remove Leading/Trailing Whitespaces - Fixes issues with extra spaces.**

"""

df.Name = df.Name.str.strip()
df.Name

"""**Handling outliers**"""

# Detect outliers in the 'Age' column using IQR

Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Age'] < lower_bound) | (df['Age'] > upper_bound)]

print("Outliers in the 'Age' column:")
display(outliers)