# -*- coding: utf-8 -*-
"""decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiGjQoBTX-slRU_HXTiNeHagDcL4P9zx

**Practical No. 4-C: Build a decision tree classifier or regressor. Control hyperparameters like tree depth to avoid overfitting. Visualize the tree.**

---
"""

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/DataSet ML/iris.csv')

print(data)
X = data.drop('species', axis=1)
y = data['species']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.tree import DecisionTreeClassifier, plot_tree
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 10))
plot_tree(clf, filled=True, feature_names=X.columns)

plt.show()