# -*- coding: utf-8 -*-
"""k-nearest Neighbor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLuMz3TuXNT6WEEK6JNHvD0ZYwyNgX1D

**Practical No. 4-B: Implement and demonstrate k-nearest Neighbor algorithm.Read the training data from a .CSV file and build the model to classify a test sample. Print both correct and wrong predictions.**

---
"""

import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
x=[4,5,10,4,3,11,14,8,10,12]
y=[21,19,24,17,16,25,24,22,21,21]
classes=[0,0,1,0,0,1,1,0,1,1]
plt.scatter(x,y,c=classes)
plt.title("k-nearest Neighbor")
plt.show()

data=list(zip(x,y))
print(data)
model=KNeighborsClassifier(n_neighbors=1)
model.fit(data,classes)
new_x=8
new_y=21
new_point=[(new_x,new_y)]
prediction=model.predict(new_point)
plt.scatter(x+[new_x],y+[new_y],c=classes+[prediction[0]])
plt.text(x=new_x+1.7,y=new_y-0.7,s=f"new_point,class:{prediction[0]}")

plt.show()

model=KNeighborsClassifier(n_neighbors=5)
model.fit(data,classes)
new_x=8
new_y=21
new_point=[(new_x,new_y)]
prediction=model.predict(new_point)
plt.scatter(x+[new_x],y+[new_y],c=classes+[prediction[0]])
plt.text(x=new_x+1.7,y=new_y-0.7,s=f"new_point,class:{prediction[0]}")

plt.show()