# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12anznOK9C9ABjlNDw472mROv-rkOZyMV

**Practical No. 4-A: Logistic Regression: For a give a set of training data examples stored in a .CSV file implement Logistic Regression algorithm.**

---
"""

import pandas as pd
dataset = pd.read_csv("/content/drive/MyDrive/DataSet ML/diabetes.csv")
print(dataset.head())
x = dataset.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7]].values
y = dataset.iloc[:, -1].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=40)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix :\n ", cm)
print("Accuracy :", accuracy_score(y_test, y_pred))