# -*- coding: utf-8 -*-
"""Multiple Linear Regression .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJM_pc4aVdIqOlsKNVYQ2a3yn2ypPakj

**Practical No. 3-B : Multiple Linear Regression Extend linear regression to multiple features. Handle feature selection and potential multicollinearity.**


---

**Step1 : Import requied libraries**
"""

import random as r
from sklearn.linear_model import LinearRegression

print("All Libraries are imported...")

"""**Step2 : Ready with Dataset**"""

feature_set = []
target_set = []

rows = 200
limit = 10
count = 0

for i in range(0,rows):
  x = r.randint(0,limit)
  y = r.randint(0,limit)
  z = r.randint(0,limit)
  g = 10*x + 2*y + 3*z
  feature_set.append([x,y,z])
  target_set.append(g)
  count += 1


print("Total Records : ",count)
print("Feature Set : ",feature_set)
print("Target Set : ",target_set)

"""**Step3:Create LinearRegression Model**"""

model = LinearRegression()
print(model)
print("Model is created...")

"""**Step4: Train LinearRegression Model**"""

model.fit(feature_set,target_set)
print("Model is trained...")

"""**Step5 : Test Linear Regression Model**"""

test_data = [[1,2,3]]
prediction = model.predict(test_data)
print("Predicted output : ",prediction," with coeff. ",model.coef_)