# -*- coding: utf-8 -*-
"""Naive Bayesian classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyP5UEFmuOMC_lRll6w64Pb3rxh-Vfe0

**Practical No. 5-AImplement and demonstrate the working of a Naive Bayesian classifier using a sample data set. Build the model to classify a test sample.**

---
"""

!pip install pgmpy
!pip install BayesianModel

import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination


print("=" * 25)

# Dataset
data = pd.DataFrame({
    'Rain': ['yes','yes','no','no','yes'],
    'Traffic': ['high','high','low','low','high'],
    'Late': ['yes','yes','no','no','yes']
})

# Model structure
model = DiscreteBayesianNetwork([
    ('Rain', 'Traffic'),
    ('Traffic', 'Late')
])

# Train model
model.fit(data, estimator=MaximumLikelihoodEstimator)

# Inference
infer = VariableElimination(model)
result = infer.query(variables=['Late'], evidence={'Rain': 'yes'})

print(result)