# -*- coding: utf-8 -*-
"""Regularized Linear Models .ipyn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7VSbuYrnVHGXJWU6CnzQMqfpAHZtHKz

**Practical No. 3-C: Regularized Linear Models (Ridge, Lasso, ElasticNet). Implement regression variants like LASSO and Ridge on any generated dataset.Regularized Linear Models(Ridge, Lasso, ElasticNet)**


---
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
# Step 1: Create the dataset
data = {
'SquareFootage': [1500, 2000, 2500, 3000],
'Bedrooms': [3, 4, 4, 5],
'AgeofHouse': [20, 15, 10, 5],
'price': [300000, 400000, 500000, 600000]
}
df = pd.DataFrame(data)
print(df)

x = df[['SquareFootage','Bedrooms','AgeofHouse']]
y = df['price']
# Step 3: Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# Step 4: Apply Ridge Regression
ridge = Ridge(alpha=1.0) # alpha is the regularization strength (入)
ridge.fit(x_train, y_train)
ridge_predictions = ridge.predict(x_test)
# Step 5: Apply Lasso Regression
lasso = Lasso(alpha=1.0) # alpha is the regularization strength (入)
lasso.fit(x_train, y_train)
lasso_predictions = lasso.predict(x_test)
# Step 6:Evaluate the models
ridge_mse = mean_squared_error(y_test, ridge_predictions)
lasso_mse = mean_squared_error(y_test, lasso_predictions)

print("Ridge Regression Coefficients:", ridge.coef_)
print("Lasso Regression Coefficients:", lasso.coef_)
print("Ridge Regression MSE:", ridge_mse)
print("Lasso Regression MSE:",lasso_mse)