# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrFiVReO0GAKlOwswTyNbSAADZPmzTot

**Practical No. 3-A : Simple Linear Regression Fit a linear regression model on a dataset.**

---

**Step1: Import Libraries**
"""

import matplotlib.pyplot as plt
from scipy import stats

print("All libraries are imported !!!")

"""**Step2 : Create dataset for Simple Regression**"""

import random
# Advertisement Budget
# x = [1,2,3,4,5,10,6,9]
# Sales
# y = [2,4,5,4,6,12,7,8]

# Advertisement Budget (randomly generated)
x = [random.randint(1, 100) for _ in range(10)]

# Sales (randomly generated, with some correlation to x)
y = [random.randint(x[i] - 10, x[i] + 10) for i in range(10)]

print("Dataset\nx:",x," y:",y)

"""**Step3 : Create Model**"""

m,c,r_value,p_value,std_err = stats.linregress(x,y)

def linearmodel(x):
  return m*x + c

"""**Step4 : Train model**"""

model = list(map(linearmodel,x))

print("Model Trained !!!")

"""**Step5: Plot model output**"""

plt.scatter(x,y)
plt.plot(x,model)
plt.xlabel("Advertisement Budget")
plt.ylabel("Sales")
plt.title("Simple Linear Regression")
plt.show()