# -*- coding: utf-8 -*-
"""Testing Hypothesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGi5LJwaVv5sI86ZzJl9Z7pyi5sEklFg

**Practical No. 2: Testing Hypothesis. Implement and demonstrate the FIND-S algorithm for finding the most specific hypothesis based on a given set of training data samples. Read the training data from a. CSV file and generate the final specific hypothesis.**

---
"""

def find_s(examples):
    # Initialize hypothesis with most specific values
    h = ['Ø'] * (len(examples[0])-1) # Corrected the TypeError here

    for example in examples:
        if example[-1] == 'Yes':
            for i in range(len(example)-1):
                if h[i] == 'Ø':
                    h[i] = example[i]
                elif h[i] != example[i]:
                    h[i] = '?'
    return h

# Sample training data
data = [
    ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'],
    ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'No'],
    ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'],
    ['Sunny', 'Warm', 'Normal', 'Weak', 'Warm', 'Same', 'Yes']
]

hypothesis = find_s(data)
print("Final Hypothesis:", hypothesis[:6]) # Sliced the hypothesis to print only the first 6 elements