# -*- coding: utf-8 -*-
"""Vector Machine .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U25OAQraUsMNQCoeYuMX4UfCHF4wIyEM

**Practical No. 4-D: Implement a Support Vector Machine for any relevant dataset.**

---
"""

# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
# Display name

print("=" * 30)
# Load dataset
data = pd.read_csv("/content/drive/MyDrive/DataSet ML/iris.csv")
print("Dataset:\n", data.head())
# Separate features and target
X = data.drop('species', axis=1)
y = data['species']
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
# Train SVM model
svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train, y_train)
# Prediction on test data
y_pred_svm = svm_classifier.predict(X_test)
# Accuracy calculation
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print("Accuracy (SVM):", accuracy_svm)
# Single sample prediction
sample = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=X.columns
)

sample_prediction = svm_classifier.predict(sample)
print("Sample Prediction:", sample_prediction)

# Plot accuracy bar chart
plt.figure(figsize=(6, 4))
plt.bar(['SVM'], [accuracy_svm])
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title("Model Accuracy")
plt.show()